### ISSUE TITLE
retsly-js-sdk 0.6.6 seems to have broken www v1

### ISSUE THREAD

**Issue by MadManMathew** [Retsly/retsly-js-sdk#39]
### Issue
Update to retsly-js-sdk doesn't set the X-Requested-With header field set to XMLHttpRequest
which thus sets the req.xhr to true breaking our application.
Code in retsly/retsly checks req.xhr to set the context of the token

### Replication Steps
1. Try to log into Retsly, calls api/v1/user/me...
2. Get 401 Unauthroized

### Expected Behavior
1. Can log in,  calls api/v1/user/me...
2. 200 OK

### Notes
I found the line, it appears XDomainRequest is undefined when i debug using chrome.
https://github.com/Retsly/retsly-js-sdk/blob/master/index.js#L224
https://github.com/Retsly/retsly-js-sdk/blob/master/index.js#L398

**Comment by slajax** [comment]
It should be undefined. XDomainRequest only exists in IE. 

This header should default to true in every other browser so it doesn't need to be set.

If you remove the condition and just always set it, does it solve your problem?

**Comment by slajax** [comment]
Further, that line functionality has been working since Oct 27, 2014 and hasn't changed, so it's confusing to me that it's not working for you all the sudden.

**Comment by MadManMathew** [comment]
let me check again

**Comment by MadManMathew** [comment]
I was wrong, cause by a different issue
https://github.com/Retsly/retsly/issues/1037
