### ISSUE TITLE
Retsly js sdk should work server side.

### ISSUE THREAD

**Issue by MadManMathew** [Retsly/retsly-js-sdk#46]
I should just be able to require('restly-js-sdk') and supply it with my clientId and broswer token and it should just work. imho. Currently it can't even ben required and when I fixed that component-ajax requiries window global

**Comment by MadManMathew** [comment]
@Jkhwan thoughts?

**Comment by slajax** [comment]
:+1: This is a great idea, and something I wanted from the start but it just didn't materialize.

**Comment by lvivier** [comment]
:+1: superagent works in both browser/node. As a lighter solution, there's also https://www.npmjs.com/package/xmlhttprequest

**Comment by slajax** [comment]
closed by #60
