### ISSUE TITLE
JS SDK version 2

### ISSUE THREAD

**Issue by Jkhwan** [Retsly/retsly-js-sdk#47]
Rewrite the JS SDK from scratch
  - using ES6 (classes)
  - work with node
  - MVP will not support oAuth
  
  
  

##### Learnings on ES6
https://github.com/ericdouglas/ES6-Learning

**Comment by slajax** [comment]
Hey @Jkhwan can this be closeD? Was it done in another PR?

**Comment by Jkhwan** [comment]
yup, this can be closed now. A new repo was created for v2 js-sdk. https://github.com/retsly/js-sdk
